### ISSUE TITLE
[Suggestion] Tebex

### ISSUE THREAD

**Issue by NxTPanic** [samerton/Nameless-Tebex#10]
Dear Samerton, 

First of all i hope you are doing okay. 

I got a qeustion if you can add the following widgets in the tebex module on namelessmc.

+ add TopDonator
+ add Full support on check out / support for the module so you don't have to get directed to buycraft.

(Maybe a usefull link for reference https://shop.thearchon.net/checkout/basket )

have an amazing day!

Br,
Jeffry

**Comment by samerton** [comment]
Hi,

I can investigate a top donator widget - should be very possible to calculate this in the Nameless side of things.

Unfortunately the checkout is handled entirely on Tebex's side so having an integrated checkout with Nameless is not possible.

**Comment by samerton** [comment]
I'll mark this as closed and link to #9 as that also requests a top donator widget.
