### ISSUE TITLE
STAFFCP NOT SHOWING TEBEX PANEL

### ISSUE THREAD

**Issue by PineAppleGrits** [samerton/Nameless-Tebex#13]
I have all the folders correctly but the tebex panel is not showing
![image](https://user-images.githubusercontent.com/66481194/89064618-b0744900-d340-11ea-821e-c364b3decdeb.png)
I also have installed the module 
![image](https://user-images.githubusercontent.com/66481194/89064633-ba964780-d340-11ea-8b2e-66f5f0a5a5f9.png)
And widgets 
![image](https://user-images.githubusercontent.com/66481194/89064650-c2ee8280-d340-11ea-9dba-0ef645eb463f.png)

**Comment by samerton** [comment]
Hi, can you please make sure you are in the group with ID 2 (StaffCP -> Configuration -> Groups) as this is the default admin group which modules add their permissions to.
