### ISSUE TITLE
[Bug] Option to enabe widgets in store not available 

### ISSUE THREAD

**Issue by JustJP2K** [samerton/Nameless-Tebex#19]
The option to enable the widget on the store page is for some reason not there... Is this intentional?
Would be kinda weird since i wouldnt want it to be enabled anywhere else than the store, for example the top purchases i would only want players to view in the store.
![image](https://user-images.githubusercontent.com/74447960/107829771-bb497500-6d8a-11eb-9738-c719138e4a35.png)

**Comment by JustJP2K** [comment]
as you can see the module tebex is enabled but its not showing up there

**Comment by JustJP2K** [comment]
@samerton The Latest Purchases widget is working fine in the index page but not on the tebex store page... any idea why?

**Comment by JustJP2K** [comment]
One of the buttons is glitched as well. where you can only click on it on the first 20% of the button. the rest it wont register

**Comment by IkiaeM** [comment]
I have a same problème with widget in store page but it's template probably

**Comment by samerton** [comment]
This does not appear to be an issue using module version 1.1.1 and the Default Revamp template so I will close this issue - if you are still experiencing issues with Default Revamp feel free to re-open.
