### ISSUE TITLE
Images not displaying on packages

### ISSUE THREAD

**Issue by gamilelmalek** [samerton/Nameless-Tebex#20]
Images not displaying on packages. Worked prior to update to pr8/9. Running the 1.1.0 version.

Images are already uploaded at `/uploads/store` with proper package ID. It seems like the images aren't getting pulled.

![image](https://user-images.githubusercontent.com/6868295/108887346-2f054080-761b-11eb-8e15-efc6614cc23d.png)

**Comment by gamilelmalek** [comment]
It was specifically not displaying on the widget. I was able to do a workaround by modifying the table in the DB.

Work around only functioned temporarily

**Comment by samerton** [comment]
Should be resolved in 0e8fd65fc71a83d70d6a8ee30e4e8b0f59b5425f
