### ISSUE TITLE
Order of price and currency in packages

### ISSUE THREAD

**Issue by FeronThal** [samerton/Nameless-Tebex#29]
It would be nice to have a possibility to change order of the price and currency in packages.
Some currencies are using currency symbol after the price, so it would be a good change.

For example: right now there is currency first and price second (€5). After change it should be the other way round (5€).

**Comment by samerton** [comment]
https://github.com/samerton/Nameless-Tebex/commit/8f57ba5d25b310da5ab32a4aa58f7a75bbab572b

**Comment by samerton** [comment]
Added in latest 1.3.0 release - requires updates to any custom templates/panel templates
