### ISSUE TITLE
The main category is seen as a sub-category

### ISSUE THREAD

**Issue by FrancyMak** [samerton/Nameless-Tebex#30]
Good evening, in my tebex I have the SkyBlock category with sub-categories outlining other things that can be purchased, but I noticed that in my NamelessMC the skyblock category is seen as the main category, even though it has no packages inside. 

![image](https://user-images.githubusercontent.com/75610581/196158324-8f8c2fb6-6595-4f16-88f2-5bba66389a1b.png)
![image](https://user-images.githubusercontent.com/75610581/196158354-ff5406a5-77bf-427c-a680-5778aa638afe.png)

**Comment by samerton** [comment]
Added in 1.3.0 - requires updates to custom templates
