### ISSUE TITLE
2.1.0 When force syncing DB::createQuery() error appears

### ISSUE THREAD

**Issue by Gyztor** [samerton/Nameless-Tebex#31]
Module just most likely needs to be updated but this may help find what parts need to be updated sooner.
![image](https://github.com/samerton/Nameless-Tebex/assets/44737827/5cb90e73-5a22-4efe-8b9a-fe8b17063993)

**Comment by didacpe** [comment]
I got the same issue:

Nameless: 2.1.0
Nameless-Tebex: 1.3.1

**Comment by samerton** [comment]
Fixed in latest release
