### ISSUE TITLE
Package image & description import

### ISSUE THREAD

**Issue by GershonR** [samerton/Nameless-Tebex#8]
The current importer lacks the ability to bring in images and descriptions for packages. By sending a request to the packages endpoint with verbose enabled that should return that data from Tebex. Here is what I did in order to get it working with sync:

```
curl_setopt($ch, CURLOPT_URL, 'https://plugin.buycraft.net/packages?verbose=true');

$ch_result = curl_exec($ch);

$result = json_decode($ch_result);

if(!isset($result->error_code)){
	$db->createQuery('TRUNCATE TABLE nl2_buycraft_packages_descriptions');

    if(count($result)){
        foreach($result as $package){
            $db->createQuery('INSERT INTO nl2_buycraft_packages_descriptions (`id`, `package_id`, `description`, `image`) VALUES (?, ?, ?, ?)', array(
                $package->id,
                $package->id,
                $package->description,
                Output::getClean($package->image),
            ));
        }
    }
}
```
I'm not too familiar with PHP, so I wasn't sure how to get the id to just auto increment in the DB.

**Comment by samerton** [comment]
At the time the module was created, Tebex did not return image or description data in their API responses.

If this has been added since, I can take a look and add it to the module for the next update. Thanks for the snippet too!

**Comment by samerton** [comment]
Thanks to @fluse1367 this will be in the next update :)
